### ISSUE TITLE
Why does the inc folder exist?

### ISSUE THREAD

**Issue by danieltj27** [jacklenox/susty#16]
I haven't tested this, so do forgive me but surely having individual files which only contain one function in an `inc` directory surely adds some HTTP overhead that can be saved, no?

Is this documented somewhere as it's something I've seen in a few WordPress themes and I'm curious as to why it's structured that way.

A quick dig through StackOverflow suggests the effects of [including files is negligible](https://stackoverflow.com/a/7885404/7236046) but it would reduce the overall theme footprint. I'd like to read your thoughts on this.

**Comment by jacklenox** [comment]
Hi @danieltj27, apologies for the delay in replying on this.

Using an `inc` directory is a convention that came about – I believe – as a means of not having one enormous `functions.php` file in a theme. This is a convention that is followed in [_s](https://github.com/automattic/_s), and as I used that theme as my base, it exists in Susty too.

You'll see that the files in the `inc` directory are used in the `functions.php` file:

https://github.com/jacklenox/susty/blob/0a086e970e7db8cc67490857a44a7c09f967411d/functions.php#L115-L135

Let me know if you have any further questions. :slightly_smiling_face:

**Comment by aristath** [comment]
> surely having individual files which only contain one function in an inc directory surely adds some HTTP overhead that can be saved, no?

Not really. These are loaded via PHP, not in the browser, so the only overhead will be the time it takes the server to read the file. Which is no more that a few picoseconds... And adding them in functions.php would increase the size of the functions.php file which in turn would make the server take those extra picoseconds to read the functions.php file.
There's no overhead, and having some things separate improves the development process since things are better organized. :+1:

**Comment by jacklenox** [comment]
Thank you @aristath, I totally neglected responding on that particular part of the question.
